apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stanaka-dev-wheres-teddy-app-dev
  annotations:
    argocd/app-name: stanaka-dev-wheres-teddy-app-dev
    backstage.io/kubernetes-id: stanaka-dev-wheres-teddy-app
    backstage.io/kubernetes-namespace: stanaka-dev
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devhub-tanaka/stanaka-dev-wheres-teddy
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - python
    - genai
    - datascience
    - nodejs
  links:
    - url: https://console-openshift-console.apps.sandbox-m4.g2pi.p1.openshiftapps.com/dev-pipelines/ns/stanaka-dev/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.sandbox-m4.g2pi.p1.openshiftapps.com/k8s/ns/stanaka-dev/deployments/stanaka-dev-wheres-teddy-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.sandbox-m4.g2pi.p1.openshiftapps.com/#https://github.com/devhub-tanaka/stanaka-dev-wheres-teddy?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "tanaka"
  consumesApis:
  - photo-generator-genai